setwd("F:\\R_Learning\\TestData\\CHM\\data")
getwd()

library(rgdal)
library(sp)
library(rgeos)
library(rgl)
library(lidR)
library(magrittr)
library(dtplyr)
library(dplyr)
library(rLiDAR)
library(raster)

LASfile <- system.file("data", "370000_5848000.las", package="lidR")
lidar15 = lidR::readLAS("370000_5848000.las")
summary(lidar15)
plot(lidar15)
dtm15 = grid_terrain(lidar15)
plot(dtm15)
